<script setup lang="ts">
import AppLayout from "@/layouts/AppLayout.vue";
import { router, useForm } from "@inertiajs/vue3";

defineOptions({ layout: AppLayout });
defineProps<{ categories: any[]; levels: any[]; degrees: any[] }>();
const categoryForm = useForm({ key: "", name: "", description: "", masonic_degree_id: "" });
const partForm = useForm({ key: "", ritual_category_id: "", name: "", description: "", counts_toward_program: false, point_value: "" });
const levelForm = useForm({ key: "", name: "", point_threshold: "" });
const createCategory = () => categoryForm.post("/platform/ritual-categories", { onSuccess: () => categoryForm.reset() });
const createPart = () => partForm.post("/platform/ritual-parts", { onSuccess: () => partForm.reset() });
const createLevel = () => levelForm.post("/platform/ritual-levels", { onSuccess: () => levelForm.reset() });
const saveCategory = (category: any) => router.put(`/platform/ritual-categories/${category.id}`, category);
const savePart = (part: any) => router.put(`/platform/ritual-parts/${part.id}`, part);
const saveLevel = (level: any) => router.put(`/platform/ritual-levels/${level.id}`, level);
const warning = (item: any) => `Changes that affect points, thresholds, or active state can affect ${item.affected_person_count} credited member record${item.affected_person_count === 1 ? "" : "s"}.`;
</script>

<template>
    <main class="mx-auto w-full max-w-6xl space-y-8 p-4 sm:p-6 lg:p-8"><header><h1 class="text-2xl font-bold">Ritual Reference</h1><p class="mt-1 text-sm text-muted-foreground">Platform-wide catalog. Stable keys cannot change. Deactivate records instead of deleting them.</p></header>
        <section class="space-y-3 rounded-lg border p-4"><h2 class="font-semibold">Categories</h2><form class="grid gap-2 md:grid-cols-4" @submit.prevent="createCategory"><input v-model="categoryForm.name" required placeholder="Category name" class="rounded border bg-background p-2" /><input v-model="categoryForm.key" placeholder="Stable key (optional)" class="rounded border bg-background p-2" /><select v-model="categoryForm.masonic_degree_id" class="rounded border bg-background p-2"><option value="">No degree</option><option v-for="degree in degrees" :key="degree.id" :value="degree.id">{{ degree.name }}</option></select><button class="rounded bg-primary px-3 py-2 text-primary-foreground">Add category</button></form><form v-for="category in categories" :key="category.id" class="rounded border p-3" @submit.prevent="saveCategory(category)"><div class="grid gap-2 md:grid-cols-5"><input v-model="category.name" required class="rounded border bg-background p-2" /><input :value="category.key" disabled aria-label="Stable category key" class="rounded border bg-muted p-2" /><select v-model="category.masonic_degree_id" class="rounded border bg-background p-2"><option :value="null">No degree</option><option v-for="degree in degrees" :key="degree.id" :value="degree.id">{{ degree.name }}</option></select><input v-model.number="category.sort_order" type="number" min="0" class="rounded border bg-background p-2" /><label class="flex items-center gap-2"><input v-model="category.is_active" type="checkbox" /> Active</label></div><textarea v-model="category.description" class="mt-2 w-full rounded border bg-background p-2" placeholder="Description" /><p class="mt-2 text-xs text-muted-foreground">{{ warning(category) }}</p><label class="mt-2 flex items-center gap-2 text-sm"><input v-model="category.confirm_impact" type="checkbox" /> Confirm any impact change</label><button class="mt-2 rounded border px-3 py-2">Save category</button></form></section>
        <section class="space-y-3 rounded-lg border p-4"><h2 class="font-semibold">Parts</h2><form class="grid gap-2 md:grid-cols-3" @submit.prevent="createPart"><select v-model="partForm.ritual_category_id" required class="rounded border bg-background p-2"><option value="" disabled>Category</option><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select><input v-model="partForm.name" required placeholder="Part name" class="rounded border bg-background p-2" /><input v-model="partForm.key" placeholder="Stable key (optional)" class="rounded border bg-background p-2" /><label class="flex items-center gap-2"><input v-model="partForm.counts_toward_program" type="checkbox" /> Counts toward program</label><input v-if="partForm.counts_toward_program" v-model.number="partForm.point_value" required type="number" min="1" placeholder="Points" class="rounded border bg-background p-2" /><button class="rounded bg-primary px-3 py-2 text-primary-foreground">Add part</button></form><div v-for="category in categories" :key="category.id" class="space-y-2"><h3 class="text-sm font-medium">{{ category.name }}</h3><form v-for="part in category.parts" :key="part.id" class="rounded border p-3" @submit.prevent="savePart(part)"><div class="grid gap-2 md:grid-cols-6"><input v-model="part.name" required class="rounded border bg-background p-2" /><input :value="part.key" disabled aria-label="Stable part key" class="rounded border bg-muted p-2" /><input v-model.number="part.sort_order" type="number" min="0" class="rounded border bg-background p-2" /><label class="flex items-center gap-2"><input v-model="part.counts_toward_program" type="checkbox" /> Points</label><input v-if="part.counts_toward_program" v-model.number="part.point_value" required type="number" min="1" class="rounded border bg-background p-2" /><label class="flex items-center gap-2"><input v-model="part.is_active" type="checkbox" /> Active</label></div><textarea v-model="part.description" class="mt-2 w-full rounded border bg-background p-2" placeholder="Description" /><p class="mt-2 text-xs text-muted-foreground">{{ warning(part) }}</p><label class="mt-2 flex items-center gap-2 text-sm"><input v-model="part.confirm_impact" type="checkbox" /> Confirm any impact change</label><button class="mt-2 rounded border px-3 py-2">Save part</button></form></div></section>
        <section class="space-y-3 rounded-lg border p-4"><h2 class="font-semibold">Program levels</h2><form class="grid gap-2 md:grid-cols-3" @submit.prevent="createLevel"><input v-model="levelForm.name" required placeholder="Level name" class="rounded border bg-background p-2" /><input v-model.number="levelForm.point_threshold" required type="number" min="1" placeholder="Point threshold" class="rounded border bg-background p-2" /><button class="rounded bg-primary px-3 py-2 text-primary-foreground">Add level</button></form><form v-for="level in levels" :key="level.id" class="grid gap-2 rounded border p-3 md:grid-cols-5" @submit.prevent="saveLevel(level)"><input v-model="level.name" required class="rounded border bg-background p-2" /><input :value="level.key" disabled aria-label="Stable level key" class="rounded border bg-muted p-2" /><input v-model.number="level.point_threshold" required type="number" min="1" class="rounded border bg-background p-2" /><label class="flex items-center gap-2"><input v-model="level.is_active" type="checkbox" /> Active</label><input v-model.number="level.sort_order" type="number" min="0" class="rounded border bg-background p-2" /><p class="text-xs text-muted-foreground md:col-span-5">{{ warning(level) }}</p><label class="flex items-center gap-2 text-sm md:col-span-4"><input v-model="level.confirm_impact" type="checkbox" /> Confirm any impact change</label><button class="rounded border px-3 py-2">Save level</button></form></section>
    </main>
</template>
