<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import InputError from '@/components/InputError.vue';
import { Link, useForm } from '@inertiajs/vue3';
import { computed } from 'vue';

defineOptions({ layout: AppLayout });
const props = defineProps<{ lodge: { id: number; name: string; timezone: string }; event: any; categories: Array<{ id: number; name: string }>; media: Array<{ id: number; filename: string }> }>();
const isNew = computed(() => !props.event.id);
const form = useForm({
    title: props.event.title ?? '', slug: props.event.slug ?? '', description: props.event.description ?? '', location_name: props.event.location_name ?? '', location_details: props.event.location_details ?? '', contact_name: props.event.contact_name ?? '', contact_email: props.event.contact_email ?? '', contact_phone: props.event.contact_phone ?? '', time_zone: props.event.time_zone ?? props.lodge.timezone,
    first_starts_at: props.event.first_starts_at ? new Date(props.event.first_starts_at).toISOString().slice(0, 16) : '', duration_minutes: props.event.duration_minutes ?? 120, rrule: props.event.rrule ?? '', event_category_id: props.event.event_category_id ?? '', visibility: props.event.visibility ?? 'public', required_qualification: props.event.required_qualification ?? '', allows_cross_lodge_reservations: Boolean(props.event.allows_cross_lodge_reservations), reservations_enabled: Boolean(props.event.reservations_enabled), guest_reservations_enabled: Boolean(props.event.guest_reservations_enabled), capacity: props.event.capacity ?? '', maximum_party_size: props.event.maximum_party_size ?? '', reminders_enabled: props.event.reminders_enabled ?? true, guest_reminders_enabled: props.event.guest_reminders_enabled ?? true, cover_media_asset_id: props.event.cover_media_asset_id ?? '',
});
const submit = () => isNew.value ? form.post(`/lodges/${props.lodge.id}/events`) : form.put(`/lodges/${props.lodge.id}/events/${props.event.id}`);
</script>

<template>
    <main class="mx-auto max-w-4xl space-y-6 p-6"><div><Link :href="`/lodges/${lodge.id}/events`" class="text-sm text-primary underline">Events</Link><h1 class="mt-2 text-2xl font-semibold">{{ isNew ? 'Create event' : 'Edit event' }}</h1></div>
        <form class="space-y-6" @submit.prevent="submit"><section class="grid gap-4 rounded-lg border p-5 md:grid-cols-2"><label class="md:col-span-2">Title<input v-model="form.title" class="mt-1 w-full rounded-md border bg-background p-2" required /><InputError :message="form.errors.title" /></label><label>Slug<input v-model="form.slug" class="mt-1 w-full rounded-md border bg-background p-2" required /><InputError :message="form.errors.slug" /></label><label>Category<select v-model="form.event_category_id" class="mt-1 w-full rounded-md border bg-background p-2"><option value="">Uncategorized</option><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select></label><label class="md:col-span-2">Description<textarea v-model="form.description" class="mt-1 min-h-28 w-full rounded-md border bg-background p-2" /></label><label>Location<input v-model="form.location_name" class="mt-1 w-full rounded-md border bg-background p-2" /></label><label>Location details<input v-model="form.location_details" class="mt-1 w-full rounded-md border bg-background p-2" /></label></section>
            <section class="grid gap-4 rounded-lg border p-5 md:grid-cols-2"><h2 class="md:col-span-2 text-lg font-medium">Schedule</h2><label>Starts<input v-model="form.first_starts_at" type="datetime-local" class="mt-1 w-full rounded-md border bg-background p-2" required /></label><label>Time zone<input v-model="form.time_zone" class="mt-1 w-full rounded-md border bg-background p-2" required /></label><label>Duration (minutes)<input v-model.number="form.duration_minutes" type="number" min="1" class="mt-1 w-full rounded-md border bg-background p-2" required /></label><label>RRULE (optional)<input v-model="form.rrule" placeholder="FREQ=WEEKLY;COUNT=12" class="mt-1 w-full rounded-md border bg-background p-2" /><InputError :message="form.errors.rrule" /></label></section>
            <section class="grid gap-4 rounded-lg border p-5 md:grid-cols-2"><h2 class="md:col-span-2 text-lg font-medium">Audience and reservations</h2><label>Visibility<select v-model="form.visibility" class="mt-1 w-full rounded-md border bg-background p-2"><option value="public">Public</option><option value="masons">Masons only</option><option value="lodge">Lodge only</option></select></label><label v-if="form.visibility !== 'public'">Qualification<select v-model="form.required_qualification" class="mt-1 w-full rounded-md border bg-background p-2"><option value="ea">Entered Apprentice</option><option value="fc">Fellow Craft</option><option value="mm">Master Mason</option><option value="pm">Past Master</option></select></label><label class="flex items-center gap-2"><input v-model="form.reservations_enabled" type="checkbox" /> Enable reservations</label><label class="flex items-center gap-2"><input v-model="form.guest_reservations_enabled" type="checkbox" /> Allow guest reservations</label><label>Capacity<input v-model.number="form.capacity" type="number" min="1" class="mt-1 w-full rounded-md border bg-background p-2" /></label><label>Maximum party size<input v-model.number="form.maximum_party_size" type="number" min="1" class="mt-1 w-full rounded-md border bg-background p-2" /></label><label class="flex items-center gap-2"><input v-model="form.allows_cross_lodge_reservations" type="checkbox" /> Allow cross-lodge reservations</label></section>
            <section class="space-y-3 rounded-lg border p-5"><h2 class="text-lg font-medium">Reminders</h2><label class="flex items-center gap-2"><input v-model="form.reminders_enabled" type="checkbox" /> Enable reminder subscriptions</label><label class="flex items-center gap-2"><input v-model="form.guest_reminders_enabled" type="checkbox" /> Allow guest reminder subscriptions</label></section>
            <button type="submit" :disabled="form.processing" class="cursor-pointer rounded-md bg-primary px-4 py-2 font-medium text-primary-foreground disabled:opacity-50">Save event</button>
        </form>
    </main>
</template>
