<script setup lang="ts">
import AppLayout from "@/layouts/AppLayout.vue";
import { Head, router } from "@inertiajs/vue3";
import { ref } from "vue";

const props = defineProps<{ categories: any[]; proficiencies: Record<string, any>; settings: any; availability: any[]; progress: any }>();
const visibilityScope = ref(props.settings.visibility_scope);
const note = ref(props.settings.public_availability_note ?? "");
const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const dayparts = ["morning", "afternoon", "evening"];
const selectedWindows = ref(new Set(props.availability.map((window: any) => `${window.day_of_week}:${window.daypart}`)));
const saveSettings = () => router.put("/ritual/settings", { visibility_scope: visibilityScope.value, public_availability_note: note.value });
const update = (part: any, values: any) => router.put(`/ritual/parts/${part.id}`, values, { preserveScroll: true });
const saved = (part: any) => props.proficiencies[String(part.id)] ?? { status: "not_known", interested_in_learning: false, willing_to_assist: false, performed_for_credit: false, first_marked_proficient_on: null, notes: "" };
const toggleWindow = (day: number, daypart: string) => { const key = `${day}:${daypart}`; if (selectedWindows.value.has(key)) selectedWindows.value.delete(key); else selectedWindows.value.add(key); selectedWindows.value = new Set(selectedWindows.value); };
const saveAvailability = () => router.put("/ritual/availability", { windows: [...selectedWindows.value].map((key) => { const [day_of_week, daypart] = key.split(":"); return { day_of_week: Number(day_of_week), daypart }; }) });
</script>

<template>
    <Head title="Ritual" />
    <AppLayout :breadcrumbs="[{ title: 'Ritual', href: '/ritual' }]">
        <main class="mx-auto w-full max-w-5xl space-y-6 p-4 md:p-6">
            <section class="rounded-lg border p-5"><h1 class="text-xl font-semibold">Ritual progress</h1><p class="mt-1 text-sm text-muted-foreground">Current points: {{ progress.current_total }}. Proficiency is self-reported; credit requires a performance from memory in an open lodge.</p></section>
            <section class="rounded-lg border p-5"><h2 class="font-semibold">Ritual visibility and availability</h2><select v-model="visibilityScope" class="mt-3 rounded border p-2"><option value="hidden">Hidden</option><option value="own_lodge">Own lodges</option><option value="participating_lodges">Participating lodges</option></select><textarea v-model="note" class="mt-3 w-full rounded border p-2" maxlength="500" placeholder="General availability note (visible only in ritual search)" /><button class="mt-2 rounded bg-primary px-3 py-2 text-primary-foreground" @click="saveSettings">Save visibility</button><p class="mt-2 text-xs text-muted-foreground">Availability is informational only and creates no commitment, booking, or assignment.</p></section>
            <section class="rounded-lg border p-5"><h2 class="font-semibold">General availability</h2><p class="mt-1 text-sm text-muted-foreground">Choose broad weekday/daypart windows. This is not a reservation or commitment.</p><div class="mt-3 overflow-x-auto"><table class="w-full text-sm"><thead><tr><th class="p-2 text-left">Day</th><th v-for="daypart in dayparts" :key="daypart" class="p-2 capitalize">{{ daypart }}</th></tr></thead><tbody><tr v-for="(day, index) in days" :key="day"><th class="p-2 text-left">{{ day }}</th><td v-for="daypart in dayparts" :key="daypart" class="p-2 text-center"><input type="checkbox" :checked="selectedWindows.has(`${index + 1}:${daypart}`)" :aria-label="`${day} ${daypart}`" @change="toggleWindow(index + 1, daypart)" /></td></tr></tbody></table></div><button class="mt-3 rounded bg-primary px-3 py-2 text-primary-foreground" @click="saveAvailability">Save availability</button></section>
            <section v-for="category in categories" :key="category.id" class="rounded-lg border p-5"><h2 class="font-semibold">{{ category.name }}</h2><div v-for="part in category.parts" :key="part.id" class="mt-4 border-t pt-4"><div class="flex flex-wrap items-center justify-between gap-2"><strong>{{ part.name }}</strong><span class="text-sm">{{ part.point_value ? `${part.point_value} points` : 'Does not count toward program points' }}</span></div><div class="mt-3 grid gap-3 md:grid-cols-2"><label>Status <select class="ml-2 rounded border p-1" :value="saved(part).status" @change="update(part, { status: ($event.target as HTMLSelectElement).value })"><option value="not_known">Not known</option><option value="learning">Learning</option><option value="proficient">Proficient</option></select></label><label><input type="checkbox" :checked="saved(part).interested_in_learning" @change="update(part, { interested_in_learning: ($event.target as HTMLInputElement).checked })" /> Interested in learning</label><label><input type="checkbox" :checked="saved(part).willing_to_assist" :disabled="saved(part).status !== 'proficient'" @change="update(part, { willing_to_assist: ($event.target as HTMLInputElement).checked })" /> Willing to assist</label><label><input type="date" :value="saved(part).first_marked_proficient_on ?? ''" @change="update(part, { first_marked_proficient_on: ($event.target as HTMLInputElement).value || null })" /> First proficient date</label></div><textarea class="mt-3 w-full rounded border p-2" :value="saved(part).notes ?? ''" maxlength="2000" placeholder="Private notes" @change="update(part, { notes: ($event.target as HTMLTextAreaElement).value || null })" /><label class="mt-3 block text-sm"><input type="checkbox" :checked="saved(part).performed_for_credit" @change="update(part, { performed_for_credit: ($event.target as HTMLInputElement).checked, confirm_performed_for_credit: ($event.target as HTMLInputElement).checked })" /> I confirm I performed this part from memory in an open lodge.</label></div></section>
            <section v-if="progress.credited_retired_parts.length" class="rounded-lg border p-5"><h2 class="font-semibold">Retired credited parts</h2><p class="mt-1 text-sm text-muted-foreground">These historical credit claims no longer count toward the current total.</p><ul class="mt-3 list-disc pl-5"><li v-for="item in progress.credited_retired_parts" :key="item.id">{{ item.part.name }}</li></ul></section>
        </main>
    </AppLayout>
</template>
