<script setup lang="ts">
const props = defineProps<{ section: any; lodge: any; media: Record<string, any>; officers: any[]; pastMasters: any[]; primaryForeground: string; secondaryForeground: string }>();
const asset = (id: number | null | undefined) => (id ? props.media[String(id)] : null);
</script>

<template>
    <section v-if="section.type === 'hero'" class="relative isolate overflow-hidden px-5 py-20 text-center sm:py-28" :style="{ backgroundColor: lodge.primary_color, color: asset(section.configuration.media_id) ? '#ffffff' : primaryForeground }">
        <img v-if="asset(section.configuration.media_id)" :src="asset(section.configuration.media_id).url" :alt="asset(section.configuration.media_id).alt_text" class="absolute inset-0 -z-20 size-full object-cover" /><div v-if="asset(section.configuration.media_id)" class="absolute inset-0 -z-10 bg-black/55"></div><h1 class="text-4xl font-bold sm:text-6xl">{{ section.configuration.heading }}</h1><p v-if="section.configuration.body" class="mx-auto mt-5 max-w-3xl text-lg">{{ section.configuration.body }}</p>
    </section>
    <section v-else-if="section.type === 'rich_text' || section.type === 'custom_html'" class="public-rich-text mx-auto max-w-4xl px-5 py-10" v-html="section.configuration.html"></section>
    <figure v-else-if="section.type === 'image'" class="mx-auto max-w-5xl px-5 py-10"><img v-if="asset(section.configuration.media_id)" :src="asset(section.configuration.media_id).url" :alt="asset(section.configuration.media_id).alt_text" class="w-full rounded-xl object-cover shadow-sm" /><figcaption v-if="section.configuration.caption" class="mt-3 text-center text-sm text-slate-600">{{ section.configuration.caption }}</figcaption></figure>
    <section v-else-if="section.type === 'image_text'" class="mx-auto grid max-w-6xl items-center gap-8 px-5 py-12 md:grid-cols-2"><img v-if="asset(section.configuration.media_id)" :src="asset(section.configuration.media_id).url" :alt="asset(section.configuration.media_id).alt_text" class="w-full rounded-xl object-cover" :class="{ 'md:order-2': section.configuration.image_side === 'right' }" /><div><h2 class="text-3xl font-bold">{{ section.configuration.heading }}</h2><p class="mt-4 whitespace-pre-line text-slate-700">{{ section.configuration.body }}</p></div></section>
    <section v-else-if="section.type === 'link_list'" class="mx-auto max-w-4xl px-5 py-10"><h2 v-if="section.configuration.heading" class="text-3xl font-bold">{{ section.configuration.heading }}</h2><ul class="mt-4 divide-y rounded-lg border"><li v-for="link in section.configuration.links" :key="link.url"><a :href="link.url" class="block px-4 py-3 font-medium hover:bg-slate-50">{{ link.label }} →</a></li></ul></section>
    <section v-else-if="section.type === 'call_to_action'" class="mx-auto my-10 max-w-5xl rounded-xl px-6 py-10 text-center" :style="{ backgroundColor: lodge.secondary_color, color: secondaryForeground }"><h2 class="text-3xl font-bold">{{ section.configuration.heading }}</h2><p v-if="section.configuration.body" class="mx-auto mt-3 max-w-2xl">{{ section.configuration.body }}</p><a :href="section.configuration.url" class="mt-6 inline-block rounded-md px-5 py-3 font-semibold" :style="{ backgroundColor: lodge.primary_color, color: primaryForeground }">{{ section.configuration.label }}</a></section>
    <section v-else-if="section.type === 'contact_information'" class="mx-auto max-w-4xl px-5 py-10"><h2 class="text-3xl font-bold">{{ section.configuration.heading || 'Contact Us' }}</h2><p v-if="section.configuration.body" class="mt-3">{{ section.configuration.body }}</p><address class="mt-5 not-italic"><p>{{ lodge.physical_address }}, {{ lodge.city }}, {{ lodge.state }}</p><p><a :href="`mailto:${lodge.public_email}`" class="underline">{{ lodge.public_email }}</a></p><p v-if="lodge.public_phone"><a :href="`tel:${lodge.public_phone}`" class="underline">{{ lodge.public_phone }}</a></p></address></section>
    <section v-else-if="section.type === 'meeting_information'" class="mx-auto max-w-4xl px-5 py-10"><h2 class="text-3xl font-bold">{{ section.configuration.heading || 'Meeting Information' }}</h2><p v-if="lodge.meeting_location" class="mt-4 font-medium">{{ lodge.meeting_location }}</p><p v-if="section.configuration.body" class="mt-3">{{ section.configuration.body }}</p></section>
   <section v-else-if="section.type === 'officers_placeholder'" class="mx-auto max-w-5xl px-5 py-10"><h2 class="text-3xl font-bold">{{ section.configuration.heading || 'Lodge Officers' }}</h2><div v-if="officers.length" class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article v-for="officer in officers" :key="`${officer.position}-${officer.name}`" class="rounded-xl border p-5"><p class="text-sm font-semibold uppercase tracking-wide text-slate-500">{{ officer.position }}</p><h3 class="mt-1 text-xl font-bold">{{ officer.name }}</h3><p v-if="officer.email" class="mt-3"><a :href="`mailto:${officer.email}`" class="underline">{{ officer.email }}</a></p><p v-if="officer.phone"><a :href="`tel:${officer.phone}`" class="underline">{{ officer.phone }}</a></p></article></div><p v-else class="mt-4 text-slate-600">{{ section.configuration.body || 'Officer information will be available soon.' }}</p></section>
    <section v-else-if="section.type === 'past_masters_placeholder'" class="mx-auto max-w-4xl px-5 py-10"><h2 class="text-3xl font-bold">{{ section.configuration.heading || 'Past Masters' }}</h2><p v-if="section.configuration.body" class="mt-3 max-w-2xl text-slate-600">{{ section.configuration.body }}</p><ol v-if="pastMasters.length" class="mt-6 overflow-hidden rounded-xl border"><li v-for="term in pastMasters" :key="`${term.year}-${term.name}`" class="grid grid-cols-[5rem_minmax(0,1fr)] items-center gap-4 border-b px-5 py-4 last:border-b-0"><span class="font-mono text-lg font-semibold text-slate-500">{{ term.year }}</span><span class="text-lg font-medium">{{ term.name }}</span></li></ol><p v-else class="mt-4 text-slate-600">Past Master records will be added soon.</p></section>
    <section v-else class="mx-auto max-w-4xl px-5 py-10"><div class="rounded-xl border border-dashed bg-slate-50 p-8 text-center"><h2 class="text-2xl font-bold">{{ section.configuration.heading }}</h2><p class="mt-3 text-slate-600">{{ section.configuration.body || 'More information will be available soon.' }}</p></div></section>
</template>
