<script setup lang="ts">
import AppearanceTabs from "@/components/AppearanceTabs.vue";
import type { SharedData } from "@/types";
import { Head, Link, router, useForm, usePage } from "@inertiajs/vue3";
import { computed, ref } from "vue";

const props = defineProps<{ events: { data: Array<any>; links: Array<any>; last_page: number }; filters: Record<string, string>; filterOptions: { groups: Array<any>; lodges: Array<any>; categories: Array<any> }; canViewProtectedEvents: boolean }>();
const page = usePage<SharedData>();
const view = ref<"list" | "calendar">("list");
const filters = useForm({ group: props.filters.group ?? "", lodge: props.filters.lodge ?? "", category: props.filters.category ?? "", visibility: props.filters.visibility ?? "", qualification: props.filters.qualification ?? "", from: props.filters.from ?? "", to: props.filters.to ?? "" });
const search = () => router.get("/events", filters.data(), { preserveState: true, replace: true });
const days = computed(() => Object.entries(props.events.data.reduce((items: Record<string, any[]>, event: any) => { const day = event.starts_at.slice(0, 10); (items[day] ??= []).push(event); return items; }, {})).map(([date, events]) => ({ date, events })));
</script>

<template>
    <Head title="WorkingTools events" />
    <main class="min-h-dvh bg-muted/30 px-5 py-8 text-foreground sm:py-12"><div class="mx-auto max-w-6xl">
        <header class="flex items-center justify-between gap-4"><Link href="/lodges" class="text-lg font-semibold">WorkingTools</Link><div class="flex gap-3"><AppearanceTabs compact /><Link :href="page.props.auth.user ? route('dashboard') : route('login')" class="rounded border bg-background px-3 py-2 text-sm">{{ page.props.auth.user ? "Portal" : "Log in" }}</Link></div></header>
        <section class="py-10"><h1 class="text-3xl font-bold sm:text-4xl">Regional events</h1><p class="mt-3 text-muted-foreground">Public events from active WorkingTools lodges.<template v-if="!canViewProtectedEvents"> Sign in to see Masonic events you qualify for.</template></p></section>
        <form class="grid gap-3 rounded-xl border bg-background p-4 md:grid-cols-4" @submit.prevent="search"><select v-model="filters.group" class="field-input"><option value="">All groups</option><option v-for="group in filterOptions.groups" :key="group.id" :value="group.slug">{{ group.name }}</option></select><select v-model="filters.lodge" class="field-input"><option value="">All lodges</option><option v-for="lodge in filterOptions.lodges" :key="lodge.id" :value="lodge.slug">{{ lodge.name }} No. {{ lodge.number }}</option></select><select v-model="filters.category" class="field-input"><option value="">All categories</option><option v-for="category in filterOptions.categories" :key="category.key" :value="category.key">{{ category.name }}</option></select><select v-model="filters.visibility" class="field-input"><option value="">All visible events</option><option value="public">Public</option><template v-if="canViewProtectedEvents"><option value="masons">Masons</option><option value="lodge">Lodge</option></template></select><input v-model="filters.from" type="date" class="field-input" aria-label="From date" /><input v-model="filters.to" type="date" class="field-input" aria-label="To date" /><select v-if="canViewProtectedEvents" v-model="filters.qualification" class="field-input"><option value="">All qualifications</option><option value="ea">Entered Apprentice</option><option value="fc">Fellow Craft</option><option value="mm">Master Mason</option><option value="pm">Past Master</option></select><button class="primary-button" :disabled="filters.processing">Apply filters</button></form>
        <div class="mt-6 flex gap-2"><button class="rounded border px-3 py-2 text-sm" :class="view === 'list' ? 'bg-primary text-primary-foreground' : ''" @click="view = 'list'">List</button><button class="rounded border px-3 py-2 text-sm" :class="view === 'calendar' ? 'bg-primary text-primary-foreground' : ''" @click="view = 'calendar'">Calendar</button></div>
        <section v-if="events.data.length && view === 'list'" class="mt-4 grid gap-4 md:grid-cols-2"><article v-for="event in events.data" :key="event.id" class="rounded-xl border bg-background p-5"><p class="text-sm text-muted-foreground">{{ event.lodge.name }} No. {{ event.lodge.number }}</p><p v-if="event.visibility !== 'public'" class="mt-2 text-xs font-medium uppercase">Members only</p><h2 class="mt-1 text-xl font-semibold">{{ event.title }}</h2><p class="mt-2 text-sm">{{ event.starts_at }}</p><p v-if="event.location_name" class="mt-1 text-sm text-muted-foreground">{{ event.location_name }}</p><a :href="event.url" class="mt-4 inline-block text-sm font-medium underline">View event</a></article></section>
        <section v-else-if="events.data.length" class="mt-4 space-y-5"><article v-for="day in days" :key="day.date" class="rounded-xl border bg-background p-5"><h2 class="font-semibold">{{ day.date }}</h2><ul class="mt-3 space-y-2"><li v-for="event in day.events" :key="event.id"><a :href="event.url" class="underline">{{ event.title }}</a> <span class="text-sm text-muted-foreground">— {{ event.lodge.name }}</span></li></ul></article></section>
        <p v-else class="mt-6 rounded-xl border bg-background p-8 text-center text-muted-foreground">No events match these filters.</p>
    </div></main>
</template>
