<script setup lang="ts">
import AppLayout from "@/layouts/AppLayout.vue";
import { Head, Link, router, useForm } from "@inertiajs/vue3";
defineOptions({ layout: AppLayout });
const props = defineProps<{ lodge: any; issues: any[]; deletedIssues: any[]; canPublish: boolean }>();
const form = useForm({ title: "", slug: "", publication_date: null as string | null, body_html: "", cover_media_asset_id: null as number | null, newsletter_document_id: null as number | null });
const remove = (issue: any) => router.delete(`/lodges/${props.lodge.id}/newsletters/manage/${issue.id}`);
</script>
<template><Head :title="`${lodge.name} newsletters`" /><main class="mx-auto max-w-5xl space-y-7 p-6"><header><h1 class="text-3xl font-bold">Newsletters</h1><p class="text-slate-600">Drafts stay private until published.</p></header><section class="divide-y rounded border"><article v-for="issue in issues" :key="issue.id" class="flex items-center gap-3 p-4"><div class="min-w-0 flex-1"><strong>{{ issue.draft?.title ?? issue.published?.title }}</strong><p class="text-sm text-slate-500">/{{ issue.slug }} · {{ issue.draft ? 'Draft' : '' }}{{ issue.draft && issue.published ? ' + ' : '' }}{{ issue.published ? 'Published' : '' }}</p></div><Link :href="`/lodges/${lodge.id}/newsletters/manage/${issue.id}/edit`" class="underline">Edit</Link><button v-if="canPublish && issue.published" class="underline" @click="router.post(`/lodges/${lodge.id}/newsletters/manage/${issue.id}/unpublish`)">Unpublish</button><button class="text-red-700 underline" @click="remove(issue)">Delete</button></article><p v-if="!issues.length" class="p-5 text-slate-600">No newsletter issues.</p></section><section class="rounded border p-5"><h2 class="text-xl font-semibold">Create issue</h2><form class="mt-4 grid gap-3 sm:grid-cols-2" @submit.prevent="form.post(`/lodges/${lodge.id}/newsletters/manage`)"><label>Title<input v-model="form.title" required class="field-input" /></label><label>Slug<input v-model="form.slug" required class="field-input" /></label><button class="w-fit rounded bg-slate-900 px-4 py-2 text-white">Create draft</button></form></section></main></template>
